"""Cross-module ports. T07 provides the concrete render-ingestion implementation."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol
from uuid import UUID


class AssetIngestionPort(Protocol):
    """M2 hands completed Compute metadata to M3 without importing M3 repositories or S3 adapters."""

    async def create_from_completed_render(self, *, render_job_id: UUID) -> None: ...


@dataclass(frozen=True, slots=True)
class OwnedAsset:
    """M4-safe ownership/readiness answer. Never contains storage keys."""

    asset_id: UUID
    owner_id: UUID
    media_type: str
    status: str
    visibility: str


@dataclass(frozen=True, slots=True)
class AssetPreview:
    """Browser-safe derivative URLs generated by M3, never raw object keys."""

    asset_id: UUID
    media_type: str
    thumbnail_url: str | None
    watermarked_preview_url: str | None
    video_poster_url: str | None


@dataclass(frozen=True, slots=True)
class PublishableAsset:
    asset: OwnedAsset
    preview: AssetPreview


class AssetReader(Protocol):
    """M3's only read dependency exposed to M4 catalogue/listing code."""

    async def find_owned_asset(self, *, asset_id: UUID, owner_id: UUID) -> OwnedAsset | None: ...

    async def find_public_preview(self, *, asset_id: UUID) -> AssetPreview | None: ...

    async def find_publishable_asset(
        self, *, asset_id: UUID, owner_id: UUID
    ) -> PublishableAsset | None: ...


class EntitlementReader(Protocol):
    """M5-owned authorization answer. M3 receives no order/payment data."""

    async def has_active_entitlement(self, *, user_id: UUID, asset_id: UUID) -> bool: ...
