#!/usr/bin/env bash
set -euo pipefail

if [[ ${EUID} -ne 0 ]]; then
  echo "Run this installer as root: sudo $0" >&2
  exit 1
fi

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
FRP_VERSION=${FRP_VERSION:-0.69.0}
FRP_SERVER_ADDR=${FRP_SERVER_ADDR:-fractal.kevin0412.top}
FRP_SERVER_PORT=${FRP_SERVER_PORT:-7000}

case "$(uname -m)" in
  x86_64)
    FRP_ARCH=amd64
    FRP_SHA256=6b90d1cd28fc661f170c0de90dde03d2c63e4fd7ce0ae2da2ca1c28014b8146e
    ;;
  aarch64|arm64)
    FRP_ARCH=arm64
    FRP_SHA256=24a4fc82b4c041835103419685ea124c4d6a7dbf83d0425481c5831b4ce4b3a4
    ;;
  *)
    echo "Unsupported architecture: $(uname -m)" >&2
    exit 1
    ;;
esac

if [[ -n ${FRP_TOKEN_FILE:-} ]]; then
  if [[ ! -r ${FRP_TOKEN_FILE} ]]; then
    echo "FRP_TOKEN_FILE is not readable: ${FRP_TOKEN_FILE}" >&2
    exit 1
  fi
  FRP_TOKEN=$(< "${FRP_TOKEN_FILE}")
else
  read -r -s -p "FRP token: " FRP_TOKEN </dev/tty
  echo >/dev/tty
fi
if [[ ! ${FRP_TOKEN} =~ ^[A-Fa-f0-9]{64}$ ]]; then
  echo "FRP token must be the 64-character hex value generated by install-frps.sh" >&2
  exit 1
fi

if command -v apt-get >/dev/null 2>&1; then
  apt-get update
  apt-get install -y --no-install-recommends ca-certificates curl tar
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y ca-certificates curl tar
else
  echo "This installer requires apt-get or dnf" >&2
  exit 1
fi

INSTALL_TMP=$(mktemp -d /tmp/frpc-install.XXXXXX)
trap 'rm -rf -- "$INSTALL_TMP"' EXIT
FRP_ARCHIVE="$INSTALL_TMP/frp.tar.gz"

curl -fL \
  "https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${FRP_ARCH}.tar.gz" \
  -o "$FRP_ARCHIVE"
printf '%s  %s\n' "$FRP_SHA256" "$FRP_ARCHIVE" | sha256sum -c -
tar -xzf "$FRP_ARCHIVE" -C "$INSTALL_TMP"
install -m 0755 \
  "$INSTALL_TMP/frp_${FRP_VERSION}_linux_${FRP_ARCH}/frpc" \
  /usr/local/bin/frpc

if ! getent group frp >/dev/null; then
  groupadd --system frp
fi
if ! id -u frp >/dev/null 2>&1; then
  useradd --system --gid frp --home-dir /nonexistent --shell /usr/sbin/nologin frp
fi
install -d -m 0750 -o root -g frp /etc/frp

cat > /etc/frp/frpc.toml <<EOF
serverAddr = "${FRP_SERVER_ADDR}"
serverPort = ${FRP_SERVER_PORT}
loginFailExit = false

auth.method = "token"
auth.token = "${FRP_TOKEN}"

transport.tls.enable = true

log.to = "console"
log.level = "info"
log.maxDays = 7

[[proxies]]
name = "fractal-ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 12222

[[proxies]]
name = "fractal-frontend"
type = "tcp"
localIP = "127.0.0.1"
localPort = 3010
remotePort = 13010

[[proxies]]
name = "fractal-platform-api"
type = "tcp"
localIP = "127.0.0.1"
localPort = 18100
remotePort = 18110

[[proxies]]
name = "fractal-minio"
type = "tcp"
localIP = "127.0.0.1"
localPort = 19010
remotePort = 19020
EOF
unset FRP_TOKEN
chown root:frp /etc/frp/frpc.toml
chmod 0640 /etc/frp/frpc.toml
install -m 0644 "$SCRIPT_DIR/frpc.service" /etc/systemd/system/frpc.service

/usr/local/bin/frpc verify -c /etc/frp/frpc.toml
systemctl daemon-reload
systemctl enable --now frpc

echo
echo "Private-host installation complete."
echo "Local listener check:"
ss -lnt | awk 'NR == 1 || /:(22|3010|18100|19010)[[:space:]]/' || true
systemctl --no-pager --full status frpc || true
